<?php
    echo "<div id='basic_page_left'>";
    echo    "<p>";
    echo        "Our video tours are designed to show the personality of your property. As they are becoming one of the most popular ways to advertise acomodation they are a must have for property owners and really make your listing stand out. We use proffesional camera men to capture your property and then a proffesional editor and high quality music to create your video tour. This gives you a classy, beautiful video which you can use to advertise your property on your social networking pages and your own website.";
    echo    "</p>";
    echo    "<p>";
    echo        "lovevideotours.com has been designed from the ground up to be easily searchable and browsable. We have always tried to simplify the site itself while making sure the content can be as rich as possible. We combine high quality video and images, recommendations, an interactive map, update facilities and search functions to provide plentiful, easily discoverable content.";
    echo    "</p>";
    echo    "<p>";
    echo        "To this end we have ended up with a site where the property and attractions are centre stage and all functionality has been removed if not deemed absolutely necessary.";
    echo    "</p>";
    echo    "<p>";
    echo        "The result is the site you see, where you can find out a lot about your holiday destination without having to wade through over complicated interfaces or unneccesary content which does not support your goals on our site.";
    echo    "</p>";
    echo    "<p>";
    echo        "We find our visitors spend time on our site becasue there is always something new to discover and the way to discover is intuitive.";
    echo    "</p>";
    echo    "<h2>Alysoun Sharpe</h2>";
    echo    "<span class='about_us_email'>(<a href='mailto:alysoun@lovevideotours.com'>alysoun@lovevideotours.com</a>)</span>     ";   
    echo    "<p>";
    echo        "After graduating from Northumbria University I set up my own business which I've now been running for several years. I have a passionate interest in Natural history, social history and local heritage and I've worked (and continue to work!) on several documentaries about Northumberland and the Scottish Borders as well as various educational films.";
    echo    "</p>";
    echo    "<p>";
    echo        "I've always loved the beauty of this area, and have a keen interest in applying my media skills to the tourism sector. I produced the first ever DVD Postcard (a video portrait of Northumberland and the Borders) in Northumberland and am looking forward to bringing these skills to you, to show the beauty of Northumberland and the Scottish Borders to a larger, potentially international audience!";
    echo    "</p>";
    echo    "<p>";         
    echo        "In my spare time I enjoy watching films (which goes without saying!), visiting ruins, going on long road trips, going to the theatre and reading. I've also recently begun rock climbing and hope to scale some big crags in Northumberland soon!";
    echo    "</p>";  
        
    echo    "<h2>Colin Sharpe</h2>";  
    echo    "<span class='about_us_email'>(<a href='mailto:colin@lovevideotours.com'>colin@lovevideotours.com</a>)</span>";  
    echo    "<p>";  
    echo        "I am an experienced web developer who has worked on a number of large, complicated web projects before getting involved with lovevideotours.com.";  
    echo    "</p>";  
    echo    "<p>";  
    echo        "After graduating with a degree in computing and working for a while at an agency where I dealt with large scale corporate projects, I decided to go freelance in order to learn and experience more about business than a developer role at an agency could teach me. This has taken me through various business development schemes including the exclusive Difference Engine, which I went through with Love Your Larder.";  
    echo    "</p>";  
    echo    "<p>";              
    echo        "All this experience has been channelled into lovevideotours.com in order to build an easy to use, technically proficient product. I am also approachable and adept at explaining technical things to those who aren't as web savvy, so feel free to contact me directly with any problems you may have with lovevideotours.com.";  
    echo    "</p>";  
    echo    "<p>";              
    echo        "Aside from lovevideotours.com I run Excited State Design, a web development agency in Alnwick and I am also into cooking, music and photography (you can see my photographs on the site in fact).";  
    echo    "</p>";  
    echo "</div>";
    echo "<div id='basic_page_right'>";
    echo    "<span class='contact_detail'><span class='cd_head'>You can email us direct at:</span><span class='cd_details'><a href='mailto:alysoun@lovevideotours.com'>alysoun@lovevideotours.com</a></span><span class='cd_details'>01668 283 465</span></span>";
    echo    "<span class='contact_detail'><span class='cd_head'>Film related enquiries:</span><span class='cd_details'><a href='mailto:alysoun@lovevideotours.com'>alysoun@lovevideotours.com</a></span><span class='cd_details'>01668 283 465</span></span>";
    echo    "<span class='contact_detail'><span class='cd_head'>Tech feedback or assistance:</span><span class='cd_details'><a href='mailto:colin@lovevideotours.com'>colin@lovevideotours.com</a></span><span class='cd_details'>07786 117 638</span></span>";
    echo "</div>";
?>