<?php
    echo "<div id='slpanel'>";
    $slc=0;
    $c=mysql_num_rows($sales_list);
    echo "<div class='slrow slsort'>";
    echo    "<span class='slname'>";
    echo        "<a href='/control-room/sales-list/stName/asc'>up</a>";
    echo        "<a href='/control-room/sales-list/stName/desc'>dn</a>";
    echo    "</span>";
    echo    "<span class='slcount'>";
    echo        "<a href='/control-room/sales-list/tourCount/asc'>up</a>";
    echo        "<a href='/control-room/sales-list/tourCount/desc'>dn</a>";
    echo    "</span>";
    echo    "<span class='sltown'>";
    echo        "<a href='/control-room/sales-list/stAddress/asc'>up</a>";
    echo        "<a href='/control-room/sales-list/stAddress/desc'>dn</a>";
    echo    "</span>";
    echo    "<span class='slcontact'>";
    echo        "<a href='/control-room/sales-list/stContact1/asc'>up</a>";
    echo        "<a href='/control-room/sales-list/stContact1/desc'>dn</a>";
    echo    "</span>";
    echo    "<span class='sltel'>";
    echo        "<a href='/control-room/sales-list/stPhone/asc'>up</a>";
    echo        "<a href='/control-room/sales-list/stPhone/desc'>dn</a>";
    echo    "</span>";
    echo    "<span class='slemail'>";
    echo        "<a href='/control-room/sales-list/stEmail/asc'>up</a>";
    echo        "<a href='/control-room/sales-list/stEmail/desc'>dn</a>";
    echo    "</span>";
    echo    "<span class='sltwitter'>";
    echo        "&nbsp;";
    echo    "</span>";
    echo    "<span class='slCat'>";
    echo        "<a href='/control-room/sales-list/stCatID/asc'>up</a>";
    echo        "<a href='/control-room/sales-list/stCatID/desc'>dn</a>";
    echo    "</span>";
    echo "</div>";
    echo "<div class='slrow slheader'>";
    echo    "<span class='slname'>";
    echo        "Target Name [1 - 10]";
    echo    "</span>";
    echo    "<span class='slcount'>";
    echo        "Count";
    echo    "</span>";
    echo    "<span class='sltown'>";
    echo        "Town";
    echo    "</span>";
    echo    "<span class='slcontact'>";
    echo        "Contact Name";
    echo    "</span>";
    echo    "<span class='sltel'>";
    echo        "Phone";
    echo    "</span>";
    echo    "<span class='slemail'>";
    echo        "Click send";
    echo    "</span>";
    echo    "<span class='sltwitter'>";
    echo        "Click follow";
    echo    "</span>";
    echo    "<span class='slCat'>";
    echo        "Category";
    echo    "</span>";
    echo "</div>";
    while ($sl=mysql_fetch_array($sales_list))
    {
        if ($slc%10==0&&$slc!=0)
        {
            if ($c<=($slc+10)) $top=$c; else $top=$slc+10;
            echo "<div class='slrow slheader'>";
            echo    "<span class='slname'>";
            echo        "Target Name [".($slc+1)." - ".$top."]";
            echo    "</span>";
            echo    "<span class='slcount'>";
            echo        "Count";
            echo    "</span>";
            echo    "<span class='sltown'>";
            echo        "Town";
            echo    "</span>";
            echo    "<span class='slcontact'>";
            echo        "Contact Name";
            echo    "</span>";
            echo    "<span class='sltel'>";
            echo        "Phone";
            echo    "</span>";
            echo    "<span class='slemail'>";
            echo        "Click send";
            echo    "</span>";
            echo    "<span class='sltwitter'>";
            echo        "Click follow";
            echo    "</span>";
            echo    "<span class='slCat'>";
            echo        "Category";
            echo    "</span>";
            echo "</div>";
        }
        if ($slc%2==0&&$slc!=0&&$slc%10!=0)
            echo "<div class='divider_feint'></div>";
        echo "<div class='slrow slentry'>";
        echo    "<span class='slname' title='".$sl["stName"]."'>";
        if (strlen($sl["stWebsite"])>0)
            if (strlen($sl["stName"])>24) echo "<a href='".$sl["stWebsite"]."' target='_blank'>".substr($sl["stName"],0,24)."</a>"; else echo "<a href='".$sl["stWebsite"]."' target='_blank'>".$sl["stName"]."</a>";
        else
            if (strlen($sl["stName"])>24) echo substr($sl["stName"],0,24); else echo $sl["stName"];
        echo    "<span class='slID'>[".$sl["stID"]."]</span>";
        echo    "</span>";
        echo    "<span class='slcount'>";
        echo        $sl["tourCount"];
        echo    "</span>";
        echo    "<span class='sltown'>";
        echo        $sl["stAddress"];
        echo    "</span>";
        echo    "<span class='slcontact'>";
        if (strlen($sl["stContact1"])>0) echo $sl["stContact1"]; else echo "&nbsp;";
        echo    "</span>";
        echo    "<span class='sltel'>";
        if (strlen($sl["stPhone"])>0) echo $sl["stPhone"]; else echo "&nbsp;";
        echo    "</span>";
        echo    "<span class='slemail' title='".$sl["stEmail"]."'>";
        if (strlen($sl["stEmail"])>0) echo "<a href='mailto:".$sl["stEmail"]."' target='_blank'>send email</a>"; else echo "&nbsp;";
        echo    "</span>";
        echo    "<span class='sltwitter'>";
        if (strlen($sl["stTwitter"])>0) echo "<a href='https://twitter.com/#!/".str_replace("@","",$sl["stTwitter"])."' target='_blank'>".$sl["stTwitter"]."</a>"; else echo "&nbsp;";
        echo    "</span>";
        echo    "<span class='slCat'>";
        echo        $sl["categoryName"];
        echo    "</span>";
        echo "</div>";
        $slc++;
    }
    echo "</div>";
?>